apiVersion: v1
kind: Namespace
metadata:
  name: cnops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterances-cnops
  namespace: cnops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utterances-cnops
  template:
    metadata:
      labels:
        app: utterances-cnops
    spec:
      containers:
      - name: utterances-cnops
        image: yellow.hub.cambricon.com/toolrd/utterances-cnops:test-6
        ports:
        - containerPort: 80   # Nginx 服务的端口
        - containerPort: 7000 # Node.js 后端服务的端口

---
apiVersion: v1
kind: Service
metadata:
  name: utterances-cnops-service
  namespace: cnops
spec:
  selector:
    app: utterances-cnops
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32760
  - name: server-port
    protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 32761
  type: NodePort
